/// Contract every entity that participates in the sync engine must satisfy.
abstract class Syncable {
  /// Stable client-side identifier (UUID v4). Generated by the client at
  /// creation time and never changes for the life of the entity.
  String get clientId;

  /// Backend-assigned identifier. Null until the first successful sync.
  String? get remoteId;

  /// Last local modification timestamp. Used for conflict detection.
  DateTime get updatedAt;

  Map<String, dynamic> toJson();
}
