import 'package:get/get.dart';

import '../../core/result/data_result.dart';
import '../../core/sync/sync.dart';
import '../../domain/entities/segmento_entity.dart';
import '../../domain/repository/segmento_repository.dart';
import '../sync/segmento_local_store.dart';

/// Reads segmentos from the local store (offline-first invariant: the UI
/// never awaits the network) and routes writes through the sync engine's
/// generic outbox.
///
/// Network operations (push/pull) happen exclusively when the user asks
/// for them through the sync page or the per-entity "forzar envío" button —
/// this class never triggers them.
class SegmentoRepositoryImpl implements SegmentoRepository {
  final OfflineRepository<SegmentoEntity> _offline;
  final SegmentoLocalStore _store;

  SegmentoRepositoryImpl({
    OfflineRepository<SegmentoEntity>? offline,
    SegmentoLocalStore? store,
  })  : _offline = offline ?? Get.find<OfflineRepository<SegmentoEntity>>(),
        _store = store ?? Get.find<SegmentoLocalStore>();

  @override
  Future<DataResult<List<SegmentoEntity>>> getByOperador(
    int operadorId,
    List<int> cts,
  ) async {
    try {
      final list = cts.isEmpty ? await _store.findAll() : await _store.findByCts(cts);
      return DataResult.success(list);
    } catch (e) {
      return DataResult.failure(
        message: 'Error leyendo segmentos locales: $e',
        cause: e,
      );
    }
  }

  @override
  Future<DataResult<SegmentoEntity?>> getById(int id) async {
    try {
      final found = await _store.findByRemoteId(id.toString());
      return DataResult.success(found);
    } catch (e) {
      return DataResult.failure(
        message: 'Error leyendo segmento $id: $e',
        cause: e,
      );
    }
  }

  /// Persists changes from a fully-formed entity (id may be null for
  /// brand-new entities created in the field). Routes through the engine:
  /// local upsert + outbox enqueue (`create` if no remote id, `update` otherwise).
  Future<SegmentoEntity> saveLocal(SegmentoEntity entity) async {
    entity.touchUpdated();
    if (entity.id == null) {
      await _offline.create(entity);
    } else {
      await _offline.update(entity);
    }
    return entity;
  }

  /// Persists a brand-new segmento created locally (no remote id yet).
  /// The entity already carries a stable [clientId] UUID generated by its
  /// constructor — no synthetic negative ids are needed.
  Future<SegmentoEntity> insertLocalOnly(SegmentoEntity entity) async {
    entity.touchUpdated();
    await _offline.create(entity);
    return entity;
  }

  @override
  Future<DataResult<bool>> updateEstado(int id, EstadoActividad estado) async {
    try {
      final entity = await _store.findByRemoteId(id.toString());
      if (entity == null) {
        return DataResult.failure(
          message: 'Segmento $id no existe en local',
          statusCode: 404,
        );
      }
      entity.estado = estado;
      entity.touchUpdated();
      await _offline.update(entity);
      return DataResult.success(true);
    } catch (e) {
      return DataResult.failure(
        message: 'Error guardando estado del segmento $id: $e',
        cause: e,
      );
    }
  }
}
